// dashboard/src/lib/widgets/Summary/Machine.svelte
<script lang="ts">
  import { GitBranch, Laptop } from "lucide-svelte";
  import Card from "../../components/Card.svelte";
  import { flowd } from "../../store.svelte";

  const OS_MAP: Record<string, string> = {
    darwin: "macos",
    linux: "linux",
  };
</script>

<Card heading="Machine">
  <div class="flex flex-col">
    <p class="text-2xl font-light">{flowd?.machine ?? "Unknown"}</p>
    <span
      class="inline-flex items-center gap-1.5 px-2 py-0.5 w-fit h-fit rounded bg-warning/20 text-warning text-[10px] font-medium"
    >
      <Laptop size={12} />
      {OS_MAP[flowd?.os] ?? flowd?.os ?? "linux"}
    </span>
  </div>
</Card>

<Card heading="Top repo">
  <div class="flex flex-col">
    <p class="text-2xl font-light">{flowd?.top_repo ?? "None"}</p>
    <span
      class="inline-flex items-center gap-1.5 px-2 py-0.5 w-fit h-fit rounded bg-warning/20 text-warning text-[10px] font-medium"
    >
      <GitBranch size={12} />
      {flowd?.top_branch ?? "main"}
    </span>
  </div>
</Card>

// dashboard-2/src/lib/widgets/machine.tsx
import { Laptop } from "lucide-react";
import { Card } from "../components/card";
import { useData } from "../context";

const OS_MAP: Record<string, string> = {
  darwin: "macos",
  linux: "linux",
};
export function MachineWidget() {
  const { data } = useData();
  return (
    <Card heading="Machine" description="">
      <p className="font-display text-2xl font-light">{data?.machine}</p>
      <span
        className="summary-widget-badge"
        style={{ "--bg": "var(--color-warning)" }}
      >
        <Laptop size={12} />
        {OS_MAP[data?.os || "linux"]}
      </span>
    </Card>
  );
}
