// dashboard/src/App.tsx
import { useCallback, useEffect, useMemo, useState } from "preact/hooks";
import type { ParsedData } from "./types";
import { Header } from "./components/Header";
import { HeroStrip } from "./components/HeroStrip";
import { ActivityHeatmap, WeekHeatmap } from "./components/Heatmap";
import { Insights } from "./components/Insights";
import { Donut } from "./components/Donut";
import { Languages } from "./components/Languages";
import { HourPattern } from "./components/HourPattern";
import { StreakCard } from "./components/StreakCard";
import { ProjectBreakdown } from "./components/ProjectBreakdown";
import { Timeline } from "./components/Timeline";
import { Summary } from "./components/Summary";
import { WeekBars } from "./components/WeekBars";
import { FlowMark } from "./components/icons";

type Theme = "dark" | "light" | "system";
const THEMES: Theme[] = ["dark", "light", "system"];
const resolveTheme = (t: Theme) =>
  t === "system"
    ? matchMedia("(prefers-color-scheme: dark)").matches
      ? "dark"
      : "light"
    : t;

function TodayView({ data }: { data: ParsedData }) {
  return (
    <main class="dashboard">
      <HeroStrip data={data} label="today" />
      <div class="grid-act">
        <ActivityHeatmap data={data} />
        <Insights data={data} />
      </div>
      <div class="grid-3">
        <Donut title="By project" subtitle="today" items={data.byProject} />
        <Donut
          title="By command"
          subtitle="today · top tools"
          items={data.byCommand.slice(0, 8)}
        />
        <Languages data={data} />
      </div>
      <div class="grid-mid">
        <HourPattern data={data} />
        <StreakCard data={data} />
        <ProjectBreakdown data={data} />
      </div>
      <div class="grid-bot">
        <Timeline data={data} />
        <Summary data={data} />
      </div>
    </main>
  );
}
function WeekView({ data }: { data: ParsedData }) {
  return (
    <main class="dashboard">
      <HeroStrip data={data} label="this week" />
      {data.weekDays.length > 0 && <WeekBars data={data} />}
      <WeekHeatmap data={data} />
      <div class="grid-3">
        <Donut title="By project" subtitle="this week" items={data.byProject} />
        <Donut
          title="By command"
          subtitle="this week"
          items={data.byCommand.slice(0, 8)}
        />
        <Languages data={data} />
      </div>
      <div class="grid-bot">
        <Timeline data={data} />
        <Summary data={data} />
      </div>
    </main>
  );
}
const EmptyState = () => (
  <main class="dashboard">
    <div class="card empty-state">
      <FlowMark size={48} />
      <h2>No activity yet</h2>
      <p>Start the daemon to begin tracking.</p>
      <p>
        <code>fw start</code>
      </p>
    </div>
  </main>
);
const WrongPeriod = ({ data, view }: { data: ParsedData; view: string }) => (
  <main class="dashboard">
    <div class="card empty-state">
      <h2>{view[0].toUpperCase() + view.slice(1)} view</h2>
      <p>This dashboard was generated for the {data.period} period.</p>
      <p>
        <code>fw dashboard {view}</code>
      </p>
    </div>
  </main>
);

export function App({ data }: { data: ParsedData }) {
  const [view, setView] = useState(data.period);
  const [theme, setTheme] = useState<Theme>(
    () => (localStorage.getItem("fw-theme") as Theme) || "system",
  );
  useEffect(() => {
    const apply = () => {
      document.documentElement.dataset.theme = resolveTheme(theme);
      localStorage.setItem("fw-theme", theme);
    };
    apply();
    const mq = matchMedia("(prefers-color-scheme: dark)");
    mq.addEventListener?.("change", apply);
    return () => mq.removeEventListener?.("change", apply);
  }, [theme]);
  const cycleTheme = useCallback(
    () => setTheme((t) => THEMES[(THEMES.indexOf(t) + 1) % THEMES.length]),
    [],
  );
  return (
    <div class="page">
      <Header
        data={data}
        view={view}
        setView={setView}
        theme={theme}
        cycleTheme={cycleTheme}
      />
      {!data.hasData ? (
        <EmptyState />
      ) : view === data.period ? (
        view === "week" ? (
          <WeekView data={data} />
        ) : (
          <TodayView data={data} />
        )
      ) : (
        <WrongPeriod data={data} view={view} />
      )}
      <footer class="foot">
        flowd<span class="dim"> — local activity tracker · self-hosted</span>
      </footer>
    </div>
  );
}

// dashboard/src/App.svelte
<script lang="ts">
  import type { RawPayload } from "./lib/types";
  import { transform } from "./lib/transform";
  import { loadTheme, cycleTheme, resolveTheme, saveTheme } from "./lib/theme";
  import Header from "./components/Header.svelte";
  import HeroStrip from "./components/HeroStrip.svelte";
  import Heatmap from "./components/Heatmap.svelte";
  import WeekHeatmap from "./components/WeekHeatmap.svelte";
  import CalHeatmap from "./components/CalHeatmap.svelte";
  import AllHeatmap from "./components/AllHeatmap.svelte";
  import Donut from "./components/Donut.svelte";
  import Languages from "./components/Languages.svelte";
  import Streak from "./components/Streak.svelte";
  import AISummary from "./components/AISummary.svelte";
  import Timeline from "./components/Timeline.svelte";
  import WeekBars from "./components/WeekBars.svelte";

  let { raw }: { raw: RawPayload } = $props();

  // Start on the period the Go command was invoked with, or "today".
  let view = $state(raw.initial_period || "today");
  let theme = $state(loadTheme());

  // Re-transform whenever the selected tab changes — all period data is already
  // embedded in the payload so this is pure CPU, no network round-trips.
  let data = $derived(transform(raw, view));

  $effect(() => {
    const resolved = resolveTheme(theme);
    document.documentElement.dataset.theme = resolved;
    document.documentElement.classList.toggle("dark", resolved === "dark");
    document.documentElement.classList.toggle("light", resolved === "light");
    saveTheme(theme);
  });
</script>

<div class="min-h-screen max-w-[1480px] mx-auto px-6 py-8 md:px-10">
  <Header {data} {view} {theme} onSetView={(v) => (view = v)} onCycleTheme={() => (theme = cycleTheme(theme))} />

  {#if !data.anyData}
    <!-- ── Global empty state (no data at all) ───────────────────── -->
    <main>
      <div class="rounded-xl border border-stone-200 dark:border-stone-800 bg-stone-50 dark:bg-stone-900
                  shadow-sm flex flex-col items-center justify-center min-h-[280px] text-center gap-3 p-8">
        <h2 class="font-display text-xl text-stone-500">No activity yet</h2>
        <p class="text-stone-400 text-xs">Start the daemon to begin tracking.</p>
        <code class="bg-stone-100 dark:bg-stone-800 px-2 py-0.5 rounded font-mono text-xs">fw start</code>
      </div>
    </main>

  {:else if !data.hasData}
    <!-- ── Period-specific empty state ───────────────────────────── -->
    <main>
      <div class="rounded-xl border border-stone-200 dark:border-stone-800 bg-stone-50 dark:bg-stone-900
                  shadow-sm flex flex-col items-center justify-center min-h-[280px] text-center gap-2.5 p-8">
        <h2 class="font-display text-xl text-stone-500">No {view} activity</h2>
        <p class="text-stone-400 text-xs">Nothing tracked for this period yet.</p>
      </div>
    </main>

  {:else if view === "today"}
    <main class="flex flex-col gap-5">
      <HeroStrip {data} label="today" />
      <div class="grid grid-cols-1 lg:grid-cols-[1.5fr_1fr] gap-5">
        <Heatmap {data} />
        <Streak {data} />
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
        <Donut title="By project" subtitle="today" items={data.byProject} />
        <Donut title="By command" subtitle="today · top tools" items={data.byCommand.slice(0, 8)} />
        <Languages {data} />
      </div>
      {#if data.aiTools.length > 0}<AISummary {data} />{/if}
      <Timeline {data} />
    </main>

  {:else if view === "week"}
    <main class="flex flex-col gap-5">
      <HeroStrip {data} label="this week" />
      {#if data.weekDays.length > 0}<WeekBars {data} />{/if}
      <WeekHeatmap {data} />
      <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
        <Donut title="By project" subtitle="this week" items={data.byProject} />
        <Donut title="By command" subtitle="this week" items={data.byCommand.slice(0, 8)} />
        <Languages {data} />
      </div>
      {#if data.aiTools.length > 0}<AISummary {data} />{/if}
      <div class="grid grid-cols-1 lg:grid-cols-[1.5fr_1fr] gap-5">
        <Timeline {data} />
        <Streak {data} />
      </div>
    </main>

  {:else if view === "month"}
    <main class="flex flex-col gap-5">
      <HeroStrip {data} label="this month" />
      <CalHeatmap {data} />
      <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
        <Donut title="By project" subtitle="this month" items={data.byProject} />
        <Donut title="By command" subtitle="this month" items={data.byCommand.slice(0, 8)} />
        <Languages {data} />
      </div>
      {#if data.aiTools.length > 0}<AISummary {data} />{/if}
      <div class="grid grid-cols-1 lg:grid-cols-[1.5fr_1fr] gap-5">
        <Timeline {data} />
        <Streak {data} />
      </div>
    </main>

  {:else if view === "year"}
    <main class="flex flex-col gap-5">
      <HeroStrip {data} label="this year" />
      <CalHeatmap {data} />
      <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
        <Donut title="By project" subtitle="this year" items={data.byProject} />
        <Donut title="By command" subtitle="this year" items={data.byCommand.slice(0, 8)} />
        <Languages {data} />
      </div>
      {#if data.aiTools.length > 0}<AISummary {data} />{/if}
      <div class="grid grid-cols-1 lg:grid-cols-[1.5fr_1fr] gap-5">
        <Timeline {data} />
        <Streak {data} />
      </div>
    </main>

  {:else if view === "all"}
    <main class="flex flex-col gap-5">
      <HeroStrip {data} label="all time" />
      <AllHeatmap {data} />
      <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
        <Donut title="By project" subtitle="all time" items={data.byProject} />
        <Donut title="By command" subtitle="all time" items={data.byCommand.slice(0, 8)} />
        <Languages {data} />
      </div>
      {#if data.aiTools.length > 0}<AISummary {data} />{/if}
      <div class="grid grid-cols-1 lg:grid-cols-[1.5fr_1fr] gap-5">
        <Timeline {data} />
        <Streak {data} />
      </div>
    </main>
  {/if}

  <footer class="flex justify-center items-center gap-1.5 mt-8 text-[11px] text-stone-400 font-mono">
    flowd <span class="text-stone-300 dark:text-stone-600">— local activity tracker</span>
  </footer>
</div>
